CREATE DATABASE SCHOOLDB;

USE SCHOOLDB;

CREATE TABLE Students(
	id INT( 11 ) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR( 50 ) NOT NULL,
	lastname VARCHAR( 100 ) NOT NULL,
	birthday DATE NOT NULL,
	address VARCHAR( 255 ) NOT NULL
);

CREATE TABLE Degrees(
	id INT( 11 ) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	country VARCHAR( 100 ) NOT NULL,
	college VARCHAR( 120 ) NOT NULL,
	period_start DATE NOT NULL,
	period_end DATE NOT NULL,
	student_id INT( 11 ) UNSIGNED NOT NULL,

	FOREIGN KEY( student_id ) REFERENCES Students( id )
);
